server:
  port: 9000
  servlet:
    context-path: /

logging:
  level:
    org.springframework.security: trace

spring:
  security:
    user:
      name: user
      password: password
  datasource:
    url: jdbc:mysql://localhost:3306/nnpia
    username: nnpia
    password: nnpia
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: YmFyYmllcHJpbmNlem55Pj5kaXNuZXlwcmluY2V6bnk=
  expiration: 3600000